title: Hi! Im Álvaro Olavarría
description: > # this means to ignore newlines until "baseurl:"
  Developer with special interest in videogames, computer graphics, software engineering, photogrammetry reconstruction and 3D art.
permalink: ':title/'
baseurl:  # the subpath of your site, e.g. /blog
url: "https://github.Alvaroolav3D.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Alvaro Olavarria Bezanilla # add your name
author-img: alvaro-olavarria.png # add your photo
about-author: "Developer with special interest in videogames, computer graphics, software engineering, photogrammetry reconstruction and 3D art." # add description
social-twitter: lvarolavarria # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: Alvaroolav3D # add your Github handle
social-linkedin: álvaro-olavarría-bezanilla # add your Linkedin handle
social-email: alvaroolavD2000@gmail.com # add your Email address

# Disqus
discus-identifier: #mr-brown # add your discus identifier

# Tracker
analytics: G-P0Z3ECKZQV # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
